export const PAYPAL_API_BASE = {
  sandbox: 'https://api-m.sandbox.paypal.com',
  production: 'https://api-m.paypal.com',
} as const;

export const PAYPAL_TOKEN_EXPIRY_BUFFER_SECONDS = 60;

export const PAYPAL_WEBHOOK_EVENTS = {
  SUBSCRIPTION_CREATED: 'BILLING.SUBSCRIPTION.CREATED',
  SUBSCRIPTION_ACTIVATED: 'BILLING.SUBSCRIPTION.ACTIVATED',
  SUBSCRIPTION_CANCELLED: 'BILLING.SUBSCRIPTION.CANCELLED',
  SUBSCRIPTION_SUSPENDED: 'BILLING.SUBSCRIPTION.SUSPENDED',
  SUBSCRIPTION_EXPIRED: 'BILLING.SUBSCRIPTION.EXPIRED',
  SALE_COMPLETED: 'PAYMENT.SALE.COMPLETED',
  SALE_DENIED: 'PAYMENT.SALE.DENIED',
  SALE_REFUNDED: 'PAYMENT.SALE.REFUNDED',
  ORDER_APPROVED: 'CHECKOUT.ORDER.APPROVED',
  ORDER_COMPLETED: 'CHECKOUT.ORDER.COMPLETED',
} as const;

export type PayPalWebhookEventType =
  (typeof PAYPAL_WEBHOOK_EVENTS)[keyof typeof PAYPAL_WEBHOOK_EVENTS];

export const PAYMENT_PROVIDER_PAYPAL = 'paypal' as const;
export const PAYPAL_DEFAULT_CURRENCY = 'USD' as const;
